#!/usr/bin/ruby
$octopus_file = ARGV[0]
if $octopus_file == nil then
  puts 'usage: octopus <same.octopus>'
  exit
end
$octopus_base = File.expand_path(File.dirname($0))

$java_command = "java -jar ";
$java_command += $octopus_base + "/translator/translator.jar "
$java_command += " " + $octopus_file

puts "Translating code..."
$result = system($java_command)
if !$result then
  exit
end
puts "done."

$trans_path = "";
if FileTest.file?($octopus_file) then
  $trans_path = File.expand_path(File.dirname($octopus_file)) + "/trans"
else
  $trans_path = File.expand_path($octopus_file) + "/trans"
end

$node_command = 'export NODE_PATH='
$node_command += $octopus_base
$node_command += '/node_modules;node '
$node_command += $trans_path + "/server.js"

puts ""
puts "Running node.js...  (exit to cmd+C)"
system($node_command)
puts ""

$rm_command = "rm -r " + $trans_path
system($rm_command)
puts "bye."
