exports.number = 3.1415;
exports.string = "i am server";
exports.t = true;
exports.f = false;
exports.u = undefined;
exports.n = null;
exports.obj = { num:1234, str:"i am server obj", bool:true };
exports.array = [3.1415, 1.4142 ];
exports.eObj = {};